/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   constants.hpp                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bguyot <bguyot@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/05/19 10:29:08 by bguyot            #+#    #+#             */
/*   Updated: 2023/05/19 11:30:24 by bguyot           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#pragma once

#define VERSION "0.2.0"

#define EXTENSIONS \
    ".123", ".3dm", ".3ds", ".max", ".accdb", .mdb (Microsoft Access)
.ai (Adobe Illustrator)
.asp, .aspx (Active Server Pages)
.asx, .wax, .wmv, .wmx (Windows Media Audio/Video)
.avi (Audio Video Interleave)
.bak, .bkf, .bup (Backup files)
.bmp (Bitmap image)
.cdr (CorelDRAW)
.cer (Security Certificate)
.class (Java class files)
.cpp (C++ source code)
.cs (C# source code)
.css (Cascading Style Sheet)
.csv (Comma-separated values)
.dbf (Database file)
.dif (Data Interchange Format)
.dip, .dip (DIPtrace PCB files)
.djvu (DjVu image)
.doc, .docx (Microsoft Word)
.dot, .dotx (Microsoft Word template)
.dwg (AutoCAD drawing)
.eml (Email message)
.fla, .swf (Adobe Flash)
.gif (Graphics Interchange Format)
.hwp (Hanword document)
.ibd (MySQL InnoDB data file)
.indd (Adobe InDesign)
.iso (Disk image)
.java (Java source code)
.jpg, .jpeg (JPEG image)
.js (JavaScript file)
.key (Apple Keynote)
.lay, .lay6 (Proteus PCB design)
.ldf (SQL Server transaction log)
.m3u (Media playlist)
.m4u (MPEG-4 playlist)
.max (Autodesk 3D Studio Max)
.mdb, .accdb (Microsoft Access)
.mdf (SQL Server database)
.mid, .midi (MIDI audio file)
.mov, .qt (QuickTime movie)
.mp3 (MP3 audio file)
.mp4 (MPEG-4 video file)
.mpeg (MPEG video file)
.msg (Outlook email message)
.myd (MySQL MyISAM data file)
.nef (Nikon RAW image)
.odb (OpenDocument Database)
.odg (OpenDocument Graphics)
.odp (OpenDocument Presentation)
.ods (OpenDocument Spreadsheet)
.odt (OpenDocument Text)
.onetoc2 (OneNote document)
.ost (Outlook offline data file)
.otg (OpenDocument Drawing template)
.otp (OpenDocument Presentation template)
.ots (OpenDocument Spreadsheet template)
.ott (OpenDocument Text template)
.p12, .pfx (PKCS #12 certificate)
.pas (Pascal source code)
.pdf (Portable Document Format)
.pem (Privacy Enhanced Mail certificate)
.php (PHP source code)
.pl (Perl script)
.png (Portable Network Graphics)
.pot, .potx (Microsoft PowerPoint template)
.ppam (PowerPoint add-in)
.pps, .ppsx (Microsoft PowerPoint slideshow)
.ppt, .pptx (Microsoft PowerPoint)
.prf (Outlook profile)
.psd (Adobe Photoshop)
.pst (Outlook personal data file)
.rar (RAR archive)
.raw (Raw image)
.rb (Ruby script)
.rtf (Rich Text Format)
.sch, .brd (Eagle PCB design)
.sldm, .sldx (Microsoft PowerPoint slide)
.sql (SQL script)
.stc (OpenOffice Calc template)
.std (Apache OpenOffice Draw template)
.sti (OpenOffice Impress template)
.stm (Exchange streaming file)
.stw (OpenOffice Writer template)
.svg (Scalable Vector Graphics)
.swf (Adobe Flash)
.sxc (OpenOffice Calc)
.sxd (OpenOffice Draw)
.sxi (OpenOffice Impress)
.sxm (OpenOffice Math)
.sxw (OpenOffice Writer)
.tar (Tape Archive)
.tbk (Toolbook)
.tgz (Gzip compressed archive)
.tif, .tiff (Tagged Image File Format)
.txt (Plain text)
.uop (Unified Office Format presentation)
.uot (Unified Office Format text)
.vb (Visual Basic script)
.vbs (VBScript file)
.vcf (vCard contact information)
.vdi (VirtualBox virtual disk image)
.vmdk (VMware virtual disk)
.vsd (Microsoft Visio)
.wav (Waveform audio file)
.wb2 (Web-based spreadsheet)
.wk1, .wks (Lotus 1-2-3)
.wma (Windows Media Audio)
.wmv (Windows Media Video)
.wpd (WordPerfect document)
.wps (Microsoft Works)
.xlc (Microsoft Excel chart)
.xlm (Microsoft Excel macro)
.xls, .xlsx (Microsoft Excel)
.xlt, .xltx (Microsoft Excel template)
.xlw (Microsoft Excel workspace)
.xml (eXtensible Markup Language)
.zip